field: ae523ce4-60b9-4674-8ed4-cbfa6ff0c20c # Button
fieldLayouts:
  da6619a7-ccfc-4768-b5a7-c580341ac8b4:
    tabs:
      -
        elements:
          -
            fieldUid: 3e5005f5-763a-459a-9bb7-74b2de70f748 # Button Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d54ca455-7ff5-451f-98e4-350b3abb1847 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 9aeeb0f0-125e-4f5f-98a5-2e7b7f3666b7 # Button Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3e5005f5-763a-459a-9bb7-74b2de70f748: # Button Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonTitle
    instructions: ''
    name: 'Button Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9aeeb0f0-125e-4f5f-98a5-2e7b7f3666b7: # Button Color
    columnSuffix: jahpdofv
    contentColumnType: text
    fieldGroup: null
    handle: buttonColor
    instructions: ''
    name: 'Button Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - button-black
            -
              - cssColour
              - black
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - button-white
            -
              - cssColour
              - white
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\buttonbox\fields\Colours
  d54ca455-7ff5-451f-98e4-350b3abb1847: # Button Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: 'Choose an entry.'
    name: 'Button Link'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: internalLink
name: 'Internal Link'
sortOrder: 1
