color: red
fieldLayouts:
  e1f0b826-8f4d-4bf3-a25f-f31ee7b19d80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-17T14:03:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 87a6fa7a-475e-4b1c-9b2c-7b2a4a67b837
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-17T14:05:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2c6e66f-5fcd-4220-b710-2624b1ef531d # Accordion Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f29155d-9f04-4230-bc58-51fd51fda594
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 662aa6ae-e48c-4ad9-914a-c4c8550c4d66
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T14:05:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e5b76ff1-163b-49c0-bd4d-718bc1b5db55 # Text Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47aedd73-8be7-4092-801b-0d6c571b67a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-17T16:11:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a75a36d-742c-4bd9-ad78-303d9f1f4b51 # Background Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af0fbeb2-33f0-4837-b98d-b713e487bc39
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 82bf36b2-4b86-4e6e-89fe-606474c33262
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T14:05:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1131725d-b336-42f4-9d4c-a9ad5ae609f5 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89565ea7-0187-42e5-b46e-ca4438f83d7c
            userCondition: null
            warning: null
            width: 100
        name: Anchor
        uid: f5a9ecc8-6f9e-425a-8475-d0ae9d13f960
        userCondition: null
handle: accordion
hasTitleField: true
icon: piano-keyboard
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
