color: null
fieldLayouts:
  a7879e4c-3900-49a8-9364-10058e05ea37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 9fa8596c-cc11-4009-8d86-3214b5170cac
            handle: button
            includeInCards: false
            instructions: null
            label: Button
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 680e6cfc-92f7-4827-98d4-8fde536f4b1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: f015d92d-b254-4665-af27-dfbe1ab2ab62
            handle: null
            includeInCards: true
            instructions: null
            label: 'Button Colour'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e327b112-7875-4b2b-9377-b40b2570eb9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea9ccc87-686f-444e-a09d-45a66c8a464a
        userCondition: null
handle: button
hasTitleField: false
icon: null
name: Button
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
