color: purple
fieldLayouts:
  0d313d7c-e4bd-435c-a7c6-a6a8fedf3b59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-21T14:39:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 165d039d-998f-4ce8-a95e-a1abc3d20c08
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T14:42:07+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'The contact form is automatically added here (setup in Freeform > Forms > Contact Form)'
            type: craft\fieldlayoutelements\Tip
            uid: c121c47d-d689-4f5b-a526-dda3d3edd1fa
            userCondition: null
        name: Content
        uid: bce81e5f-2c11-4bef-a1b4-3e6d175ff539
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-21T14:42:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e5b76ff1-163b-49c0-bd4d-718bc1b5db55 # Text Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcadfa83-8703-42b2-838e-ec52cc02181c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T14:42:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a75a36d-742c-4bd9-ad78-303d9f1f4b51 # Background Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 996ac04d-1862-45d1-a001-3ebb9b4c9a74
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 7e8c4d2a-4a6c-4f0c-8ad0-1152222a1ee3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-21T14:42:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1131725d-b336-42f4-9d4c-a9ad5ae609f5 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66d7441e-5631-47fa-9761-7ae8e8b78cea
            userCondition: null
            warning: null
            width: 100
        name: Anchor
        uid: 699b21ee-2c27-4cb1-b87d-34350b586e6f
        userCondition: null
handle: contactForm
hasTitleField: true
icon: envelope-open-text
name: 'Contact Form'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
