color: orange
fieldLayouts:
  671c917e-e1bc-4ef0-9412-e1e9ea940dd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-24T09:59:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f64efd3-101a-4ed1-a31e-96657d6dc6e5 # Header
            handle: embedCode
            includeInCards: false
            instructions: 'Copy and paste your embed code here'
            label: 'Embed Code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3af4055-ad6f-4d64-b73a-db88fdc9f9b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45a7348a-b02b-4fcf-ae84-3874f29a6512
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-24T09:59:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a75a36d-742c-4bd9-ad78-303d9f1f4b51 # Background Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43607608-2eee-4669-8761-36ecbaa9a960
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 66e1ded8-2f03-4671-826a-704ea5c471ed
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-24T09:59:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1131725d-b336-42f4-9d4c-a9ad5ae609f5 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 765c1340-91cd-4126-a34b-7c75029faa14
            userCondition: null
            warning: null
            width: 100
        name: Anchor
        uid: 12bf8c31-5279-46f6-b1d8-a6b31b0cfc9b
        userCondition: null
handle: embed
hasTitleField: false
icon: code
name: Embed
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Embed Code'
titleTranslationKeyFormat: null
titleTranslationMethod: site
