fieldLayouts:
  f5c95668-587e-4459-8b0a-5e51bfb4e8e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa9c21d4-a73d-48bf-8491-cfeb03579f32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: d783368e-a494-4457-9e99-5a027ae72a18
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64c8b243-0783-496a-9f27-46f8872acb37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1d1d5665-5674-4388-8d46-9b87e4dc65d3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a2fd304-db0d-46d3-9576-eeb7b45d27e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93a61a15-afa9-4918-91c3-6324d80e24c8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 39237593-ff51-4bd3-851a-a9dfac329c0b # Page Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfda1ff0-b04a-4c23-8d75-cec0a0b41ecc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 0ffba24e-268b-4f2c-a3f2-ad976b64c979 # Image
            handle: summaryImage
            includeInCards: false
            instructions: null
            label: 'Summary Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86c9400b-889c-47cc-95c4-a5eb63d7c1d1
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 5cef136a-926a-4cf7-8662-0891e1aa37ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 7c5c4db7-bc5e-4979-a31b-6b7734989556 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ec728ad-6232-4d54-8245-72066c1f1963
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fa50bb0d-5f14-4113-bf64-66b7eda6148c
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
