color: orange
fieldLayouts:
  726b7011-5231-497b-8666-3054c3271812:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T11:43:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0ffba24e-268b-4f2c-a3f2-ad976b64c979 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d30b8a-a0d4-4851-ba36-d8d53e7feeef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47784eb3-4990-4fa9-b60b-6543c11542e1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T16:11:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a75a36d-742c-4bd9-ad78-303d9f1f4b51 # Background Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db152e8e-b385-48d8-8d2d-93aed1f96c92
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 6008dc91-375e-4a92-a81f-a3e5493c8827
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T11:47:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1131725d-b336-42f4-9d4c-a9ad5ae609f5 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c16dc9f-6212-4a89-9422-0d293bdae526
            userCondition: null
            warning: null
            width: 100
        name: Anchor
        uid: 35fbbb51-9a88-44a5-bdac-705423837ad0
        userCondition: null
handle: image
hasTitleField: false
icon: image-landscape
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Image
titleTranslationKeyFormat: null
titleTranslationMethod: site
