color: null
fieldLayouts:
  e5166699-4103-4dbe-8f15-7722d35cd4fb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 39237593-ff51-4bd3-851a-a9dfac329c0b # Page Summary
            handle: header
            includeInCards: true
            instructions: null
            label: Header
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7048d11-bef8-4e0c-af50-5df5583bebeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 274ff3e6-0547-4a77-b718-8e29ee5b3a81
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: af138c57-8687-435f-a51f-816bf2840485
        userCondition: null
handle: item
hasTitleField: false
icon: null
name: Item
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
