color: cyan
fieldLayouts:
  b343522b-ba11-4073-9a6f-af5737b1fefb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T11:21:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01ecd9f7-e352-4f7f-a669-b89c0dcfc428
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7678c2d7-a0b8-4692-898b-b1757f6d4c0c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T11:21:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e5b76ff1-163b-49c0-bd4d-718bc1b5db55 # Text Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adc39284-1818-4b98-978b-7b97bcc32751
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-17T16:13:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a75a36d-742c-4bd9-ad78-303d9f1f4b51 # Background Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c3ef369-98bd-4482-a4b1-fa818c9a2fa2
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: b6ad45fd-0f1e-4378-a2a7-b9cdfec81e37
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T11:46:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1131725d-b336-42f4-9d4c-a9ad5ae609f5 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0451cb34-0947-4e97-8468-ac6a79ef4668
            userCondition: null
            warning: null
            width: 100
        name: Anchor
        uid: ea67767a-2743-4187-a3dd-6c0c6cbaaea8
        userCondition: null
handle: textBlock
hasTitleField: false
icon: font-case
name: 'Text Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Text Block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
