defaultPlacement: end
fieldLayouts:
  1efd367a-c84f-4741-aaf8-a888e4981005:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 35dcf37c-1c8a-441b-8233-79cb3b219ba1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8cae974b-598d-4f75-b87b-9feda7237f62
        userCondition: null
handle: newsCategories
name: 'News Categories'
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_NAME
    hasUrls: true
    template: latest/category/index.twig
    uriFormat: 'latest/category/{slug}'
structure:
  maxLevels: 1
  uid: 897bfafb-1679-4ec3-a974-3aad1f7d1bf5
