defaultPlacement: end
handle: mainNavigation
instructions: null
maxNodes: null
name: 'Main Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: none
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_NAME
    enabled: true
sortOrder: 2
structure:
  maxLevels: null
  uid: a7557cc5-d262-4681-9269-d6275d98085c
