childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  003478d0-9e28-4a83-a5dd-ff383e71ac3b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2f64efd3-101a-4ed1-a31e-96657d6dc6e5 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee1de810-fe59-4071-8f96-bebd57787671
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2c6e66f-5fcd-4220-b710-2624b1ef531d # Accordion Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3805a97-c392-41a2-9af6-7fa8ab601508
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: dc0fe483-d1b0-445f-b93d-08eb902a0595
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3615d7cc-02a0-4555-a635-1b9768172427
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 561d7596-ced1-49c9-8b13-eeb4d0f1033d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbf1de56-c0a6-4778-91db-f5f84b49fc64
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 5b7aa440-80d2-4add-a8a7-cc3adb3e6ae9
        userCondition: null
group: 9c3f9dfb-fbb4-4ab1-b8db-5dc9b6045f2d # Blocks
groupChildBlockTypes: true
handle: accordion
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Accordion
sortOrder: 5
topLevel: true
