childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  c705231b-b246-4128-a5ba-89771e0420d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ae523ce4-60b9-4674-8ed4-cbfa6ff0c20c # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bb0ec03-10ca-428f-b155-c6f5b54a30c9
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: 80b081a8-4541-4b55-9a52-8e32ab58d6cc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2efa7318-54c7-48d5-9a8b-96f42b48648d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8797d2b2-7e7a-4f8d-8771-7b828ced39ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94e6ba7c-f9c8-42f3-85fe-4db177ffb63f
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 9048fd5c-fa7d-4457-a85f-ea7f4dc692a7
        userCondition: null
group: 9c3f9dfb-fbb4-4ab1-b8db-5dc9b6045f2d # Blocks
groupChildBlockTypes: true
handle: button
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Button
sortOrder: 3
topLevel: true
