childBlocks: null
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  99e9a34b-f717-4b29-8c2b-75b95fd83d8f:
    tabs:
      -
        elements:
          -
            fieldUid: ae523ce4-60b9-4674-8ed4-cbfa6ff0c20c # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
group: dcc7e763-cfad-42ba-a4ed-f0c111f2446b # Media
handle: button
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Button
sortOrder: 4
topLevel: true
