childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  09f21b0b-1728-4107-8524-245797d45dd7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af3d9522-bb36-46a4-8da0-3a69853d38bb
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: 9001bbd2-cf5b-4b17-b0b7-8d9236f39999
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2c575f-4cb0-4c12-aa2b-57a05348ec75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04ebbbd7-e46f-45cf-bfd3-f2d5a45a6702
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c80eabd-b8e5-497f-bb1a-38a6b47af047
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: c0294107-b807-417a-a1da-88628b8efd41
        userCondition: null
group: 9c3f9dfb-fbb4-4ab1-b8db-5dc9b6045f2d # Blocks
groupChildBlockTypes: true
handle: copy
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Copy
sortOrder: 9
topLevel: true
