childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  23c4dcb1-93ba-444b-bd77-2baaeff349bd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2f64efd3-101a-4ed1-a31e-96657d6dc6e5 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8fa38e0-d7d3-4e6b-8200-2d05fcaf189c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d0dfc594-439a-40f9-8d15-a5ba6a0a5a1b # Header Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 103aec7b-2bb0-4f2b-97c9-57b38b88cb12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 876acaa4-cad8-4ddb-b96f-1a25037ad2ed # Header Type Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e82a43c1-2b5d-4107-b1fb-3f90a486107c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d7eb6cb-ab6f-462f-b9ee-719061830781 # Font Weight
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c4c9d6e-4ccc-4f0d-8111-4fd9f063f3e4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 655727c3-da54-481f-bdf5-2b7e5d13900a
        userCondition: null
group: 9c3f9dfb-fbb4-4ab1-b8db-5dc9b6045f2d # Blocks
groupChildBlockTypes: true
handle: header
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Header
sortOrder: 10
topLevel: true
