childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  de116c4b-6fdd-4504-a503-62e66fb88f12:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2f64efd3-101a-4ed1-a31e-96657d6dc6e5 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be55429a-3c35-4533-a932-38aa67acff43
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 181f8d87-6d88-42ed-96e8-26a3a728eef8 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32e24209-f325-492c-bab9-23a4b25ce667
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: cd257785-f9dd-4003-8988-3108ee6eb645
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc8b49a6-bbbd-4a63-aa98-9a5238267257
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d15880a-abf9-4c85-a0fc-c2c83f01b814
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cef4f976-7ad9-4bda-829c-8f7b45ebc48f
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: dac95b78-c644-4b28-ab3a-81e69af1fd1b
        userCondition: null
group: dcc7e763-cfad-42ba-a4ed-f0c111f2446b # Media
groupChildBlockTypes: true
handle: imageSlider
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Image Slider'
sortOrder: 3
topLevel: true
