childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  37e023cb-c31a-4e1a-b46d-a4164379789e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0ffba24e-268b-4f2c-a3f2-ad976b64c979 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 840405b0-a6a4-4181-9720-8be014ecda84
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: ea9d421f-5110-4e3e-beb5-2c777241e369
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b575582-b60b-473a-945d-9d638e57eac6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6490ce9-d270-45d8-93f5-e3ea8ff823d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec6b9015-087e-4cc1-97d1-5a177ebee0a2
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 54c9e198-6d41-4ee5-9c1a-fbc03f4dbe2b
        userCondition: null
group: dcc7e763-cfad-42ba-a4ed-f0c111f2446b # Media
groupChildBlockTypes: true
handle: image
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
sortOrder: 13
topLevel: true
