childBlocks: ''
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  de116c4b-6fdd-4504-a503-62e66fb88f12:
    tabs:
      -
        elements:
          -
            fieldUid: 181f8d87-6d88-42ed-96e8-26a3a728eef8 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: imageSlider
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Image Slider'
sortOrder: 5
topLevel: true
