childBlocks: null
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  acd3f82d-ea92-47c8-bb73-21b19ea31ede:
    tabs:
      -
        elements:
          -
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 24301a2b-def0-4ce7-baf1-9b424815122c # Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
group: 9c3f9dfb-fbb4-4ab1-b8db-5dc9b6045f2d # Blocks
handle: largeQuote
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Large Quote'
sortOrder: 10
topLevel: true
