childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  03c18548-0607-4a8e-a998-5d9e52dc4106:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Please enter the coordinates of the place you want to centre on the map.'
            type: craft\fieldlayoutelements\Tip
            uid: 8975aea2-c3cf-4087-892a-adc40f44005b
            userCondition: null
          -
            elementCondition: null
            fieldUid: c4480af9-afa8-430b-b22c-e0eddbe00de3 # Map Coordinates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b446fada-44d3-4d62-b689-eda4c8b60671
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: d90f7fed-6f91-4f8b-8824-072c9533a2fb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9748215c-afe7-43ed-954d-38c62e56fd3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f355e86d-d649-4bda-bfe4-837c3f6726a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c351553-dba9-42dc-86e7-d3b3bbd6c84c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 8ae27b05-498f-4ee9-aef4-e23882d7e069
        userCondition: null
group: dcc7e763-cfad-42ba-a4ed-f0c111f2446b # Media
groupChildBlockTypes: true
handle: map
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Map
sortOrder: 13
topLevel: true
