childBlocks: null
field: 1d1d5665-5674-4388-8d46-9b87e4dc65d3 # Content Builder
fieldLayouts:
  fc66525b-bb11-463d-b99c-a432fd9a511a:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Please enter the coordinates of the place you want to centre on the map.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: c4480af9-afa8-430b-b22c-e0eddbe00de3 # Map Coordinates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 336f207f-f4fb-43c3-bbc3-f10b641e940a # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c4a2320-184d-4f3b-9482-070fc8b8194a # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb3731df-a01f-4725-9f8b-06d99359fd9f # Top Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
group: dcc7e763-cfad-42ba-a4ed-f0c111f2446b # Media
handle: map
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Map
sortOrder: 4
topLevel: true
