childBlocks: null
field: d783368e-a494-4457-9e99-5a027ae72a18 # Page Header
fieldLayouts:
  e1f9e612-d23b-4cc4-8d06-403a136247b6:
    tabs:
      -
        elements:
          -
            fieldUid: 2f64efd3-101a-4ed1-a31e-96657d6dc6e5 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b0ce80c-181f-4c40-bcce-5146dc8c903e # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
group: null
handle: videoHeader
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Video Header'
sortOrder: 2
topLevel: true
