childBlocks: null
conditions: null
description: ''
enabled: true
field: d783368e-a494-4457-9e99-5a027ae72a18 # Page Header
fieldLayouts:
  6d751960-1e6c-40ce-8ed3-b8fc1e7fcad1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2f64efd3-101a-4ed1-a31e-96657d6dc6e5 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4425c0c7-a3fa-46ea-9799-8d55e876f695
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b0ce80c-181f-4c40-bcce-5146dc8c903e # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37b31eb6-1afe-43d1-b568-22aea1eb3f33
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: 6217ec13-3227-4a1e-a646-ea0e4ee2fba3
        userCondition: null
group: null
groupChildBlockTypes: true
handle: videoHeader
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Video Header'
topLevel: true
