fieldLayouts:
  fb641ed6-1774-49a8-b49c-3115773f5bb0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b07e41d7-6e99-422c-aa6c-e7629a3a752a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8626142-7090-4151-bff3-8cb22f973696
        userCondition: null
fs: local
handle: uploads
name: Uploads
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
