columnSuffix: null
contentColumnType: string
handle: accordionMatrix
instructions: null
name: 'Accordion Matrix'
searchable: false
settings:
  entryTypes:
    -
      uid: 80190ffa-9de6-4824-befb-1c21b98c9752
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
