columnSuffix: null
contentColumnType: text
fieldGroup: 431efb4a-9ace-451f-8b70-aeda20b1f83f # Globals
handle: address
instructions: ''
name: Address
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 6ac042db-b73d-43c5-b994-c51077efd7dc # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
