columnSuffix: null
contentColumnType: text
handle: backgroundColour
instructions: null
name: 'Background Colour'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - bg-white
        -
          - cssColour
          - FFFFFF
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - bg-black
        -
          - cssColour
          - '000000'
        -
          - default
          - ''
  placeholderText: 'Select an option'
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Colours
