columnSuffix: null
contentColumnType: text
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: backgroundColor
instructions: ''
name: 'Background Color'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - bg-white
        -
          - cssColour
          - '#FFFFFF'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - bg-black
        -
          - cssColour
          - '#000000'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Colours
