columnSuffix: null
contentColumnType: text
handle: bottomSpacing
instructions: null
name: 'Bottom Spacing'
searchable: false
settings:
  columnType: string
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - showLabel
          - '1'
        -
          - value
          - pb-default
        -
          - imageUrl
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - showLabel
          - '1'
        -
          - value
          - 'pb-lg-3 pb-md-3 pb-3'
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Larger
        -
          - showLabel
          - '1'
        -
          - value
          - 'pb-lg-5 pb-md-5 pb-4'
        -
          - imageUrl
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
