columnSuffix: null
contentColumnType: string
handle: button
instructions: null
name: Button
searchable: false
settings:
  entryTypes:
    -
      uid: fea296bc-90b6-49bf-8aac-b065d489368b
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
