columnSuffix: null
contentColumnType: string
fieldGroup: b4718bab-e938-4b97-a8e4-adc9fe5f4ca7 # Content Builder
handle: contentBuilder
instructions: ''
name: 'Content Builder'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
