columnSuffix: null
contentColumnType: text
fieldGroup: 70f3e289-0ffa-4d8a-a2a4-e8c6db06ee3c # Content Builder Fields
handle: copy
instructions: ''
name: Copy
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 6ac042db-b73d-43c5-b994-c51077efd7dc # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
