columnSuffix: null
contentColumnType: text
handle: copy
instructions: null
name: Copy
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 6ac042db-b73d-43c5-b994-c51077efd7dc # Default
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
