contentColumnType: text
fieldGroup: 431efb4a-9ace-451f-8b70-aeda20b1f83f # Globals
handle: email
instructions: ''
name: Email
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
