columnSuffix: yfbgcian
contentColumnType: text
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: fontWeight
instructions: 'You can change the weight of your font here by selecting Thin, Regular, or Bold (Regular by default)'
name: 'Font Weight'
searchable: false
settings:
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - Regular
        -
          - showLabel
          - '1'
        -
          - value
          - ''
        -
          - imageUrl
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Bold
        -
          - showLabel
          - '1'
        -
          - value
          - font-weight-bold
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Thin
        -
          - showLabel
          - '1'
        -
          - value
          - font-weight-light
        -
          - imageUrl
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
