columnSuffix: null
contentColumnType: text
fieldGroup: 431efb4a-9ace-451f-8b70-aeda20b1f83f # Globals
handle: googleAnalytics
instructions: ''
name: 'Google Analytics'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
