columnSuffix: null
contentColumnType: text
handle: header
instructions: 'Tip: Use the return key to force a new line'
name: Header
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
