columnSuffix: kfvplxon
contentColumnType: text
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: headerTypeSize
instructions: 'Use these buttons to switch the font size of the header (heading is H2 by default).'
name: 'Header Type Size'
searchable: false
settings:
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - H1
        -
          - showLabel
          - '1'
        -
          - value
          - h1
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H2
        -
          - showLabel
          - '1'
        -
          - value
          - h2
        -
          - imageUrl
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - H3
        -
          - showLabel
          - '1'
        -
          - value
          - h3
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H4
        -
          - showLabel
          - '1'
        -
          - value
          - h4
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H5
        -
          - showLabel
          - '1'
        -
          - value
          - h5
        -
          - imageUrl
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
