columnSuffix: jnfbxgmy
contentColumnType: string(7)
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: headerColour
instructions: 'Use this colour picker to update the text colour of your header'
name: 'Header Colour'
searchable: false
settings:
  defaultColor: '#000000'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
