columnSuffix: null
contentColumnType: string
handle: mapCoordinates
instructions: null
name: 'Map Coordinates'
searchable: false
settings:
  entryTypes:
    -
      uid: 308d7a68-be55-4f59-b9a4-c108480bd78f
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
