columnSuffix: null
contentColumnType: string
fieldGroup: 70f3e289-0ffa-4d8a-a2a4-e8c6db06ee3c # Content Builder Fields
handle: mapCoordinates
instructions: ''
name: 'Map Coordinates'
searchable: false
settings:
  contentTable: '{{%matrixcontent_mapcoordinates}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
