columnSuffix: vqkqrydt
contentColumnType: string(7)
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: overlayColour
instructions: 'Pick the colour to overlay your background image'
name: 'Overlay Colour'
searchable: false
settings:
  defaultColor: '#000000'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
