columnSuffix: sszkpdrw
contentColumnType: 'decimal(2,1)'
handle: overlayOpacity
instructions: null
name: 'Overlay Opacity'
searchable: false
settings:
  decimals: 1
  defaultValue: 0.6
  max: 1
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
