columnSuffix: null
contentColumnType: string
fieldGroup: b4718bab-e938-4b97-a8e4-adc9fe5f4ca7 # Content Builder
handle: pageHeader
instructions: ''
name: 'Page Header'
searchable: false
settings:
  maxBlocks: '1'
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
