columnSuffix: jcxtpype
contentColumnType: boolean
handle: showOverlay
instructions: 'Enable this switch to add a coloured overlay on top of your background image (can help overlaying text stand out better)'
name: 'Show Overlay'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
