columnSuffix: wthqjdnc
contentColumnType: string
handle: spacerOptions
instructions: null
name: 'Spacer Options'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - spacer--small
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - spacer--medium
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - spacer--large
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Extra Large'
        -
          - value
          - spacer--extra-large
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
