columnSuffix: tvhourzi
handle: textColour
instructions: 'Pick a font colour (black by default). Click for more colour presets. '
name: 'Text Colour'
searchable: false
settings:
  allowCustomColors: true
  palette:
    -
      __assoc__:
        -
          - color
          - '#000000'
        -
          - label
          - Black
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - color
          - '#ffffff'
        -
          - label
          - White
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
