columnSuffix: tvhourzi
contentColumnType: string(7)
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: textColour
instructions: 'Use this colour picker to change the colour of your body text'
name: 'Text Colour'
searchable: false
settings:
  defaultColor: '#000000'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
