columnSuffix: null
contentColumnType: text
handle: topSpacing
instructions: null
name: 'Top Spacing'
searchable: false
settings:
  columnType: string
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - showLabel
          - '1'
        -
          - value
          - pt-default
        -
          - imageUrl
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - showLabel
          - '1'
        -
          - value
          - 'pt-lg-3 pt-md-3 pt-3'
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Larger
        -
          - showLabel
          - '1'
        -
          - value
          - 'pt-lg-5 pt-md-5 pt-4'
        -
          - imageUrl
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
