columnSuffix: null
contentColumnType: text
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: topSpacing
instructions: ''
name: 'Top Spacing'
searchable: false
settings:
  displayAsGraphic: ''
  displayFullwidth: ''
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - showLabel
          - '1'
        -
          - value
          - pt-default
        -
          - imageUrl
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - showLabel
          - '1'
        -
          - value
          - 'pt-lg-3 pt-md-3 pt-3'
        -
          - imageUrl
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Large
        -
          - showLabel
          - '1'
        -
          - value
          - 'pt-lg-5 pt-md-5 pt-4'
        -
          - imageUrl
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: supercool\buttonbox\fields\Buttons
