columnSuffix: mwqygpzo
contentColumnType: boolean
fieldGroup: 7bbeec1d-6526-44a3-9897-d6d1e5918a05 # Settings
handle: transparentNav
instructions: 'Make the navigation bar on the top of the webpage transparent.'
name: 'Transparent Nav'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
