contentColumnType: string
fieldGroup: 70f3e289-0ffa-4d8a-a2a4-e8c6db06ee3c # Content Builder Fields
handle: video
instructions: 'Please choose only one of the following: External Video or Asset Video.'
name: Video
searchable: false
settings:
  contentTable: '{{%matrixcontent_video}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
