columnSuffix: null
contentColumnType: string
handle: video
instructions: 'Please choose only one of the following: External Video or Asset Video.'
name: Video
searchable: false
settings:
  entryTypes:
    -
      uid: ead943da-9146-4b32-9f33-8096b522e085
    -
      uid: 49b4d1ac-0f61-42c6-a482-63eefaa8933e
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
