field: 13d35453-527a-4094-b642-42292f193f8c # Social Profiles
fieldLayouts:
  f73678d2-2b29-48d7-99ef-179a914dc502:
    tabs:
      -
        elements:
          -
            fieldUid: 1f6a1dc8-82d8-47a8-ae54-01af20652730 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5cd6ad16-cb88-45ba-b275-1558f8f27c05 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a596aec7-c8ec-49d7-ab4d-97dcdf5ac990 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9aafe6e-671c-45da-9958-ccb6470336d6 # Alt Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f6a1dc8-82d8-47a8-ae54-01af20652730: # Name
    contentColumnType: text
    fieldGroup: null
    handle: socialName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5cd6ad16-cb88-45ba-b275-1558f8f27c05: # Link
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a596aec7-c8ec-49d7-ab4d-97dcdf5ac990: # Icon
    contentColumnType: string
    fieldGroup: null
    handle: socialIcon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: ''
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: ''
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d9aafe6e-671c-45da-9958-ccb6470336d6: # Alt Icon
    contentColumnType: string
    fieldGroup: null
    handle: altSocialIcon
    instructions: ''
    name: 'Alt Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: ''
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: ''
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
