fieldLayouts:
  d4df5b39-edcc-44f4-9b34-c6e29bad800d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Copy
            handle: address
            includeInCards: false
            instructions: null
            label: Address
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21705cd2-2215-48c3-a8a1-f1034e2bd75e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 39237593-ff51-4bd3-851a-a9dfac329c0b # Page Summary
            handle: email
            includeInCards: false
            instructions: null
            label: Email
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3017d340-97f6-4189-8b3a-05a9656a8b79
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 39237593-ff51-4bd3-851a-a9dfac329c0b # Page Summary
            handle: phoneNumber
            includeInCards: false
            instructions: null
            label: 'Phone Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2cf0ee4-0251-4bc6-8a2e-8748b0b1bccd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 13d35453-527a-4094-b642-42292f193f8c # Social Profiles
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05a7687e-ac80-4276-bb6f-c7069fa7d0f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c9a5f5ed-a985-42c6-8306-6279fc58eae6
        userCondition: null
handle: companyInfo
name: 'Company Info'
sortOrder: 1
