fieldLayouts:
  d87532ee-0145-4e34-b2e3-e16412c1cd0a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21099864-a26f-4136-b586-8740696f369a
            userCondition: null
            warning: null
            width: 100
        name: 'Main Content'
        uid: a2895ada-9a0f-49eb-bab1-9a6f6ad74641
        userCondition: null
handle: footerDisclaimer
name: 'Footer Disclaimer'
sortOrder: 3
