fieldLayouts:
  d87532ee-0145-4e34-b2e3-e16412c1cd0a:
    tabs:
      -
        elements:
          -
            fieldUid: 1d1c9f28-39de-4df6-b077-856d16c001ca # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
handle: footerDisclaimer
name: 'Footer Disclaimer'
sortOrder: 3
