fieldLayouts:
  f2d8768a-cbb9-4a52-a62f-3cebeccc956b:
    tabs:
      -
        elements:
          -
            fieldUid: 3f092924-7454-4778-a975-9d6112f3eb20 # Google Analytics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: siteInfo
name: 'Site Info'
