defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 76ee93ec-459e-4fa9-967f-aa9b48f7b9e1 # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: contact/index
    uriFormat: '{slug}'
type: single
