defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ed9d2994-c74c-40fe-9f3f-280fe7a5360a # Default
handle: customPages
maxAuthors: 1
name: 'Custom Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: a431c6e7-1793-473a-8b15-ac94a7c3f468
type: structure
