defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 369ea60f-6259-4683-adcc-23418cf8285e # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
