defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d305657a-b071-42af-960e-aa7b81715a02 # Latest
handle: latest
maxAuthors: 1
name: Latest
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: latest/_entry
    uriFormat: 'latest/{slug}'
type: channel
