enableVersioning: true
handle: latestIndex
name: 'Latest Index'
propagationMethod: all
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # Craft CMS Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: latest/_index
    uriFormat: latest
type: single
