defaultPlacement: end
enableVersioning: true
handle: latestIndex
name: 'Latest Index'
propagationMethod: all
siteSettings:
  18d78006-3985-4ea4-b620-67bae10d9c2d: # $SITE_URL
    enabledByDefault: true
    hasUrls: true
    template: latest/index
    uriFormat: latest
type: single
